// Assembles captured block images into a PDF via @react-pdf/renderer (spec §9).
// Imported dynamically from the reports modal so react-pdf stays out of the
// initial bundle — it's only pulled in when a user actually exports.
import {
  pdf, Document, Page, View, Text, Image, StyleSheet,
} from '@react-pdf/renderer';

export type ReportBlockImage = { title: string; image: string };

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#09090b',
    paddingTop: 48,
    paddingHorizontal: 40,
    paddingBottom: 56,
  },
  brand: {
    fontSize: 10,
    letterSpacing: 2,
    color: '#a1a1aa',
    marginBottom: 6,
  },
  title: {
    fontSize: 20,
    color: '#fafafa',
    fontWeight: 700,
  },
  subtitle: {
    fontSize: 10,
    color: '#71717a',
    marginTop: 6,
  },
  rule: {
    marginTop: 16,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#27272a',
  },
  block: {
    marginBottom: 18,
  },
  blockTitle: {
    fontSize: 9,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#71717a',
    marginBottom: 6,
  },
  image: {
    width: '100%',
    borderRadius: 8,
  },
  footer: {
    position: 'absolute',
    bottom: 28,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#52525b',
    textAlign: 'center',
  },
});

export async function buildReportPdf(opts: {
  title: string;
  subtitle: string;
  generatedAt: string;
  blocks: ReportBlockImage[];
}): Promise<Blob> {
  const doc = (
    <Document title={opts.title}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>CODEX</Text>
        <Text style={styles.title}>{opts.title}</Text>
        <Text style={styles.subtitle}>
          {opts.subtitle} · generated {opts.generatedAt}
        </Text>
        <View style={styles.rule} />

        {opts.blocks.map((b, i) => (
          <View key={i} style={styles.block} wrap={false}>
            <Text style={styles.blockTitle}>{b.title}</Text>
            <Image src={b.image} style={styles.image} />
          </View>
        ))}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Generated by Codex · page ${pageNumber} of ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  );
  return pdf(doc).toBlob();
}
