import { createClient } from '@/utils/supabase/server';
import { createAdminClient } from '@/utils/supabase/admin';
import { NextRequest, NextResponse } from 'next/server';
import { assertSameOrigin, getClientIp, rateLimit, requireCsrf, toErrorResponse } from '@/utils/api/guards';
import { callGroq } from '@/utils/api/groq';
import { escapeHtml, safeFilenamePart } from '@/utils/api/html';
import { parseExportPayload } from '@/utils/api/validation';

export async function POST(request: NextRequest) {
  try {
    assertSameOrigin(request);
    requireCsrf(request);
    await rateLimit(`export:${getClientIp(request)}`, { limit: 10, windowMs: 60_000 });

    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const admin = createAdminClient();
    const { range: days, template } = parseExportPayload(await request.json());
    const userId = user.id;

    const since = new Date(Date.now() - days * 86400000).toISOString();

    const { data: logs, error } = await admin
      .from('logs')
      .select('*')
      .eq('user_id', userId)
      .gte('timestamp', since)
      .order('timestamp', { ascending: false });

    if (error) throw error;

    const executiveSummary = await callGroq([
      {
        role: 'system',
        content:
          'Write a 3-5 sentence executive summary for a business report based on these logs. Focus on key achievements, financial status, and urgent tasks. Tone: Professional, Concise.',
      },
      { role: 'user', content: JSON.stringify(logs) },
    ]);

    const htmlContent = `
      <html>
        <body style="font-family: sans-serif; padding: 40px; color: #333;">
          <h1 style="border-bottom: 2px solid #000; padding-bottom: 10px;">CODEX: ${escapeHtml(template)}</h1>
          <p style="color: #666;">Generated on ${escapeHtml(new Date().toLocaleDateString())} for the last ${days} days</p>
          <div style="background: #f4f4f5; padding: 20px; border-radius: 12px; margin: 20px 0;">
            <h2 style="margin-top: 0;">Executive Summary</h2>
            <p>${escapeHtml(executiveSummary)}</p>
          </div>
          <h2>Key Logs</h2>
          ${(logs || [])
            .slice(0, 50)
            .map(
              (log) => `
            <div style="border-bottom: 1px solid #eee; padding: 10px 0;">
              <div style="font-size: 10px; color: #999;">${escapeHtml(new Date(log.timestamp).toLocaleString())} | ${escapeHtml(log.category)}</div>
              <div style="font-size: 14px; white-space: pre-wrap;">${escapeHtml(log.raw_content)}</div>
            </div>`
            )
            .join('')}
          <div style="margin-top: 40px; font-size: 10px; color: #ccc; text-align: center;">Generated by Codex AI Reporting System</div>
        </body>
      </html>`;

    return new Response(htmlContent, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="Codex_Report_${safeFilenamePart(template)}.html"`,
      },
    });
  } catch (error) {
    console.error('api/export error:', error);
    return toErrorResponse(error);
  }
}
