import { createClient } from '@/utils/supabase/server';
import { createAdminClient } from '@/utils/supabase/admin';
import { NextRequest, NextResponse } from 'next/server';

async function callGroq(messages: any[]) {
  const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.GROQ_API_KEY}`,
    },
    body: JSON.stringify({ model: 'llama-3.3-70b-versatile', messages, stream: false }),
  });
  if (!res.ok) throw new Error(`Groq error ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return data.choices[0].message.content;
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const admin = createAdminClient();
    const { range, template } = await request.json();
    const userId = user.id;

    const days = parseInt(range) || 30;
    const since = new Date(Date.now() - days * 86400000).toISOString();

    const { data: logs, error } = await admin
      .from('logs')
      .select('*')
      .eq('user_id', userId)
      .gte('timestamp', since)
      .order('timestamp', { ascending: false });

    if (error) throw error;

    const executiveSummary = await callGroq([
      {
        role: 'system',
        content:
          'Write a 3-5 sentence executive summary for a business report based on these logs. Focus on key achievements, financial status, and urgent tasks. Tone: Professional, Concise.',
      },
      { role: 'user', content: JSON.stringify(logs) },
    ]);

    const htmlContent = `
      <html>
        <body style="font-family: sans-serif; padding: 40px; color: #333;">
          <h1 style="border-bottom: 2px solid #000; padding-bottom: 10px;">CODEX: ${template}</h1>
          <p style="color: #666;">Generated on ${new Date().toLocaleDateString()} for the last ${days} days</p>
          <div style="background: #f4f4f5; padding: 20px; border-radius: 12px; margin: 20px 0;">
            <h2 style="margin-top: 0;">Executive Summary</h2>
            <p>${executiveSummary}</p>
          </div>
          <h2>Key Logs</h2>
          ${(logs || [])
            .slice(0, 50)
            .map(
              (log) => `
            <div style="border-bottom: 1px solid #eee; padding: 10px 0;">
              <div style="font-size: 10px; color: #999;">${new Date(log.timestamp).toLocaleString()} | ${log.category}</div>
              <div style="font-size: 14px;">${log.raw_content}</div>
            </div>`
            )
            .join('')}
          <div style="margin-top: 40px; font-size: 10px; color: #ccc; text-align: center;">Generated by Codex AI Reporting System</div>
        </body>
      </html>`;

    return new Response(htmlContent, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="Codex_Report_${template.replace(/\s/g, '_')}.html"`,
      },
    });
  } catch (error: any) {
    console.error('api/export error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
